# Generated by Django 5.1.5 on 2025-01-21 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opi', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PostbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=15)),
                ('opi', models.IntegerField()),
                ('short_number', models.CharField(max_length=10)),
                ('sent_count', models.IntegerField(default=0)),
                ('notification_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_text', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('created_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('postback_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo.postbackrequest')),
            ],
        ),
    ]
